const colors = {
  light: {
    text: "#0f0f0f",
    tint: "#7C3AED",
    background: "#F8F7FF",
    foreground: "#0f0f0f",
    card: "#FFFFFF",
    cardForeground: "#0f0f0f",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#4C1D95",
    muted: "#F3F0FF",
    mutedForeground: "#6B7280",
    accent: "#DDD6FE",
    accentForeground: "#4C1D95",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E8E3FF",
    input: "#E8E3FF",
    success: "#10B981",
  },
  dark: {
    text: "#F9FAFB",
    tint: "#A78BFA",
    background: "#0D0D1A",
    foreground: "#F9FAFB",
    card: "#1A1A2E",
    cardForeground: "#F9FAFB",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#2D2B55",
    secondaryForeground: "#C4B5FD",
    muted: "#1E1B3A",
    mutedForeground: "#9CA3AF",
    accent: "#3D3580",
    accentForeground: "#DDD6FE",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#2D2B55",
    input: "#2D2B55",
    success: "#34D399",
  },
  radius: 14,
};

export default colors;
